### ISSUE TITLE
Please cite PyComplexHeatmap

### ISSUE THREAD

**Issue by DingWB** [GilbertHan1011/TrajAtlas#10]
Hello @GilbertHan1011 ,

I noticed that you used PyComplexHeatmap to plot some heatmap in your paper, but you didn't cite PyComplexHeatmap paper.
Please cite it:
Ding, W., Goldberg, D. and Zhou, W. (2023), PyComplexHeatmap: A Python package to visualize multimodal genomics data. iMeta e115. [https://doi.org/10.1002/imt2.115IF: 23.7 Q1](https://doi.org/10.1002/imt2.115)
DOI: [10.1002/imt2.115IF: 23.7 Q1](https://onlinelibrary.wiley.com/doi/10.1002/imt2.115)
PMID: [38454967](https://pubmed.ncbi.nlm.nih.gov/38454967/)

**Comment by GilbertHan1011** [comment]
I will cite it in the revision. Thanks for providing the wonderful package!
